filter:
    paths: [src/*]
    excluded_paths: [tests/*]

checks:
    php:
        code_rating: true
        duplication: true
        variable_existence: true
        useless_calls: true
        use_statement_alias_conflict: true
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        unused_methods: true
        unreachable_code: true
        sql_injection_vulnerabilities: true
        security_vulnerabilities: true
        precedence_mistakes: true
        precedence_in_conditions: true
        parameter_non_unique: true
        no_property_on_interface: true
        no_non_implemented_abstract_methods: true
        deprecated_code_usage: true
        closure_use_not_conflicting: true
        closure_use_modifiable: true
        avoid_useless_overridden_methods: true
        avoid_conflicting_incrementers: true
        assignment_of_null_return: true

tools:

  external_code_coverage:
    timeout: 1800

  php_code_sniffer: true

  php_sim: true

  php_changetracking: true

  php_cs_fixer:
    config: { level: psr2 }

  php_mess_detector: true

  php_pdepend:
    enabled: true
    excluded_dirs: [tests]

  php_analyzer: true

  php_cpd:
    enabled: true
    excluded_dirs: [tests]

  php_loc:
    enabled: true
    excluded_dirs: [tests]

