before_commands:
  - composer install --dev

filter:
  paths: [src/*]
  excluded_paths: [tests/*, vendor/*]

tools:
  php_cs_fixer:
    config: { level: psr2 }

  external_code_coverage:
    timeout: 1800
