filter:
  paths: [src/*]
  excluded_paths: [tests/*]

tools:

  external_code_coverage:
    timeout: 1800

  php_cs_fixer:
    config: { level: psr2 }

  php_code_sniffer: true
  php_cpd:
    enabled: true
    excluded_dirs: [tests]
  php_pdepend:
    enabled: true
    excluded_dirs: [tests]
  php_loc:
    enabled: true
    excluded_dirs: [tests]
  php_mess_detector: true
  php_analyzer: true